name: Publish packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish (NuGet)
      uses: brandedoutcast/publish-nuget@v2  
      with:   
        PROJECT_FILE_PATH: Lib/Lib.csproj
        PROJECT_NAME: Lmpessoa.Mainframe
        BUILD_CONFIGURATION: Release
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    - name: Publish (Github)
      run: dotnet nuget add source --username Lmpessoa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
