name: Publish packages

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Add Github source
      if: always()
      run: dotnet nuget add source --name "github.com" "https://nuget.pkg.github.com/Lmpessoa/index.json"
    - name: Publish (GitHub)
      run: dotnet nuget push Lib/bin/Release/*.nupkg --api-key ${{ secrets.API_KEY_GITHUB }} --skip-duplicate --source "github.com"
    - name: Publish (NuGet)
      run: dotnet nuget push Lib/bin/Release/*.nupkg --api-key ${{ secrets.API_KEY_NUGET }} --skip-duplicate --source "nuget.org"
